# Generated by Django 5.0.3 on 2024-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.FloatField(default=0),
        ),
    ]
