# Generated by Django 5.0.3 on 2024-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_post_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
