# Generated by Django 5.0.3 on 2024-04-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0007_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Gender',
            new_name='gender',
        ),
    ]
