# Generated by Django 5.0.3 on 2024-05-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0011_userinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='idUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.userinfo'),
        ),
    ]
